package com.powernode.crm.settings.mapper;

import com.powernode.crm.settings.pojo.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_user
//     *
//     * @mbggenerated Sat Oct 21 11:45:39 CDT 2023
//     */
//    int deleteByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_user
//     *
//     * @mbggenerated Sat Oct 21 11:45:39 CDT 2023
//     */
//    int insert(User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_user
//     *
//     * @mbggenerated Sat Oct 21 11:45:39 CDT 2023
//     */
//    int insertSelective(User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_user
//     *
//     * @mbggenerated Sat Oct 21 11:45:39 CDT 2023
//     */
//    User selectByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_user
//     *
//     * @mbggenerated Sat Oct 21 11:45:39 CDT 2023
//     */
//    int updateByPrimaryKeySelective(User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tbl_user
//     *
//     * @mbggenerated Sat Oct 21 11:45:39 CDT 2023
//     */
//    int updateByPrimaryKey(User record);
    User selectUserByLoginActAndPwd(Map<String,Object> map);

    /**
     * 查询所有的用户，返回list集合
     * @return
     */
    List<User> selectAll();
}